### ISSUE TITLE
Cannt run on RTX 30 series GPU

### ISSUE THREAD

**Issue by dxyzx0** [MolecularAI/Reinvent#26]
This repo needs `cudatoolkit=10.1.243` but RTX 30 series GPU needs cuda version >= 11.1.
If I create env from `reinvent_shared.v2.1` it just cannot run.
If I create env with `pytorch=1.8.0` and `cudatoolkit=11.1.74` it will throw out error
```
Traceback (most recent call last):
  File "/home/user/fyr/Reinvent//input.py", line 25, in <module>
    main()
  File "/home/user/fyr/Reinvent//input.py", line 21, in main
    manager.run()
  File "/data/user/Reinvent/running_modes/manager.py", line 95, in run
    job()
  File "/data/user/Reinvent/running_modes/manager.py", line 41, in _run_transfer_learning
    runner.run()
  File "/data/user/Reinvent/running_modes/transfer_learning/transfer_learning_runner.py", line 29, in run
    self._train_epoch(epoch, self._config.input_smiles_path)
  File "/data/user/Reinvent/running_modes/transfer_learning/transfer_learning_runner.py", line 43, in _train_epoch
    loss.backward()
  File "/home/user/anaconda3/envs/reinvent_shared.v2.1/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/user/anaconda3/envs/reinvent_shared.v2.1/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```
How can I make this repo work on 30 series GPU?
Thank you very much!

**Comment by patronov** [comment]
We have released version 3.0 which should be (hopefully) compatible with newer versions of pytorch - specifically with 1.7.
Note that there are some other third party dependencies so best try installing through the provided *.yml.

**Comment by argentumgun** [comment]
@DingXiangYuanZhiXing 
after created the virtual environment I encountered the same problem, then I installed nvidia driver 470.86 and cuda11.3, activate reinvent environment and enter the followings:
pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

Hope this helps you

**Comment by AdrienCerdan** [comment]
I encountered the same issue while running Reinvent.3.2 with a RTX3060. I succeed to make it work with cudatoolkit=11.0.221 while sticking with pytorch=1.7.1
