### ISSUE TITLE
configs/config.json absent from installation instructions

### ISSUE THREAD

**Issue by j3mdamas** [MolecularAI/Reinvent#30]
Hi,
When doing a run, if the `configs/config.json` is not done, this is faced:

```
Traceback (most recent call last):
  File "/progs/all/opensource/reinvent/3.0/source/input.py", line 20, in <module>
    manager = Manager(configuration)
  File "/progs/all/opensource/reinvent/3.0/source/running_modes/manager.py", line 13, in __init__
    self._load_environmental_variables()
  File "/progs/all/opensource/reinvent/3.0/source/running_modes/manager.py", line 22, in _load_environmental_variables
    with open(os.path.join(project_root, '../configs/config.json'), 'r') as f:
```

It is mentioned on the `README.md`, but only on the Tests section, which can be misleading when installing Reinvent. Very minor, but thought I should mention it.

**Comment by patronov** [comment]
Thanks, yeah I realized this isnt very clear as I got quite the number of related issues.

**Comment by charlesxu90** [comment]
Same error happens to me. Seems there's an error with the defult config file. 

The question is where is the corrent path?

**Comment by charlesxu90** [comment]
I found a same issue, which has a solution.
https://github.com/MolecularAI/Reinvent/issues/35
