### ISSUE TITLE
from reinvent_scoring.scoring.scoring_function_parameters import ScoringFuncionParameters

### ISSUE THREAD

**Issue by ilknuricke-Takeda** [MolecularAI/Reinvent#31]
this import statement is failing all over the place due to the typo.

it should be ScoringFunctionParameters and not ScoringFuncionParameters because it is that way in the reinvent_scoring package. I had to manually install reinvent_chemistry, reinvent_models and reinvent_scoring and also create the json.config file

**Comment by patronov** [comment]
I suspect you have installed version of reinvent-scoring that is different from `reinvent-scoring==0.0.41`.
We have fixed the typo in the later library releases but we havent updated the public git repo.
There are also other breaking changes in the later versions that may not be entirely compatible with the repository published here. Therefore best use the libraries suggested in the reinvent.yml for the time being.

**Comment by xuzhang5788** [comment]
@ilknuricke-Takeda 
When I ran examples at ReinventCommunity/notebooks, I got the error messages:

Traceback (most recent call last):
  File "../../Reinvent/input.py", line 6, in <module>
    from running_modes.manager import Manager
  File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 4, in <module>
    from running_modes.configurations import GeneralConfigurationEnvelope
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/__init__.py", line 2, in <module>
    from running_modes.configurations.scoring import ScoringRunnerComponents, ScoringRunnerConfiguration
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/__init__.py", line 1, in <module>
    from running_modes.configurations.scoring.scoring_runner_components import ScoringRunnerComponents
  File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/scoring_runner_components.py", line 3, in <module>
    from reinvent_scoring.scoring import ScoringFuncionParameters
ModuleNotFoundError: No module named 'reinvent_scoring'

You can see that the function name was still "ScoringFuncionParameters", I changed it into ScoringFunctionParameters two places in file "Reinvent/running_modes/configurations/scoring/scoring_runner_components.py" and also in file "Reinvent.v3.0/running_modes/configurations/reinforcement_learning/reinforcement_learning_components.py". I am not sure where else still has this typo. I pip install  reinvent_chemistry, reinvent_models, and reinvent_scoring, but errors are still there. 

Traceback (most recent call last):
  File "../../Reinvent.v3.0/input.py", line 6, in <module>
    from running_modes.manager import Manager
  File "/home/xzhang/projects/Reinvent.v3.0/running_modes/manager.py", line 4, in <module>
    from running_modes.configurations import GeneralConfigurationEnvelope
  File "/home/xzhang/projects/Reinvent.v3.0/running_modes/configurations/__init__.py", line 2, in <module>
    from running_modes.configurations.scoring import ScoringRunnerComponents, ScoringRunnerConfiguration
  File "/home/xzhang/projects/Reinvent.v3.0/running_modes/configurations/scoring/__init__.py", line 1, in <module>
    from running_modes.configurations.scoring.scoring_runner_components import ScoringRunnerComponents
  File "/home/xzhang/projects/Reinvent.v3.0/running_modes/configurations/scoring/scoring_runner_components.py", line 5, in <module>
    from reinvent_scoring.scoring import ScoringFunctionParameters
ModuleNotFoundError: No module named 'reinvent_scoring'

In reinvent.v3.0 virtual environment, I import reinvent_scoring, it works. I don't know why it didn't work in ReinventCommunity virtual environment. 
Your suggestions are highly appreciated. Thanks
