### ISSUE TITLE
Unpickling error

### ISSUE THREAD

**Issue by Shiska07** [MolecularAI/Reinvent#32]
Hi, I am getting this error while trying to run the 
Complete_Use-Case-DRD2_Demo notebook in ReinventCommunity

(reinvent.v3.0) ubuntu@ip-172-31-47-40:~/repos/Reinvent2/Reinvent$ python /home/ubuntu/repos/Reinvent/input.py /home/ubuntu/repos/OutputS/DRD2_config.json
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 31, in _load_model
    activity_model = self._load_container(parameters)
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 38, in _load_container
    scikit_model = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x00'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/repos/Reinvent/input.py", line 21, in <module>
    manager.run()
  File "/home/ubuntu/repos/Reinvent/running_modes/manager.py", line 16, in run
    runner = RunningMode(self.configuration)
  File "/home/ubuntu/repos/Reinvent/running_modes/constructors/running_mode.py", line 22, in __new__
    return ReinforcementLearningModeConstructor(configuration)
  File "/home/ubuntu/repos/Reinvent/running_modes/constructors/reinforcement_learning_mode_constructor.py", line 20, in __new__
    scoring_function = ScoringFunctionFactory(config.scoring_function)
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/scoring_function_factory.py", line 16, in __new__
    return cls.create_scoring_function_instance(sf_parameters, scoring_function_registry)
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/scoring_function_factory.py", line 25, in create_scoring_function_instance
    return scoring_function(parameters, sf_parameters.parallel)
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/function/custom_sum.py", line 13, in __init__
    super().__init__(parameters, parallel)
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/function/base_scoring_function.py", line 62, in __init__
    self.scoring_components = factory.create_score_components()
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/score_components/score_component_factory.py", line 69, in create_score_components
    return [self._current_components.get(p.component_type)(p) for p in self._parameters]
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/score_components/score_component_factory.py", line 69, in <listcomp>
    return [self._current_components.get(p.component_type)(p) for p in self._parameters]
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 16, in __init__
    self.activity_model = self._load_model(parameters)
  File "/home/ubuntu/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 33, in _load_model
    raise Exception(f"The loaded file {parameters.model_path} isn't a valid scikit-learn model")
Exception: The loaded file /home/ubuntu/repos/ReinventCommunity/notebooks/models/drd2.pkl isn't a valid scikit-learn model

I would really appreciate it if you could let me know what's causing this issue.

**Comment by patronov** [comment]
Hi, Some of the models are unfortunately corrupt. We will be updating these soon.
@GuoJeff please update this issue once resolved.

**Comment by GuoJeff** [comment]
Hi @Shiska07,

I have re-uploaded the corrupt drd2.pkl model.

**Comment by xuzhang5788** [comment]
@Shiska07 
Did you run notebook or from the terminal? Which version did you use?
I used version3 and ran it in the notebook. But I got different errors 

Traceback (most recent call last):
File "../../Reinvent/input.py", line 6, in
from running_modes.manager import Manager
File "/home/xzhang/projects/Reinvent/running_modes/manager.py", line 4, in
from running_modes.configurations import GeneralConfigurationEnvelope
File "/home/xzhang/projects/Reinvent/running_modes/configurations/init.py", line 2, in
from running_modes.configurations.scoring import ScoringRunnerComponents, ScoringRunnerConfiguration
File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/init.py", line 1, in
from running_modes.configurations.scoring.scoring_runner_components import ScoringRunnerComponents
File "/home/xzhang/projects/Reinvent/running_modes/configurations/scoring/scoring_runner_components.py", line 3, in
from reinvent_scoring.scoring import ScoringFuncionParameters
ModuleNotFoundError: No module named 'reinvent_scoring'

I still can not figure out it. Can you successfully go through the notebooks? If yes, could you please share it with me? Many thanks

**Comment by GuoJeff** [comment]
Hi @Shiska07 and @xuzhang5788,

I recently re-uploaded corrupt files and pushed changes for the release of the new version of REINVENT (3.0 now). Would you be able to pull the new changes in reinvent and reinvent community, re-install the conda environments, and try the notebooks again?

**Comment by j3mdamas** [comment]
@xuzhang5788 your error is different, you're probably using an older environment, which doesn't have the new pip modules like reinvent_scoring. I'd recommend a new environment from scratch, following the instructions on reinvent 3.0

**Comment by xuzhang5788** [comment]
@j3mdamas 
Thank you for your reply. I reinstalled reinvent3.0 and everything is going well.

**Comment by Shiska07** [comment]
I have been using the latest version and everything is working fine so far. Than you for your help!
